name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm (global)
        run: npm install -g pnpm@9

      - name: Show pnpm version
        run: pnpm --version

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'


      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Test (with coverage)
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: Upload coverage artifact (optional)
        if: ${{ hashFiles('coverage/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
